#! /bin/bash

# GLOBAL VARIABLES FOR INSTALLATION SCRIPT

HOME_DIR="${HOME_DIR:-/home/vagrant}"

# Node Network parameters
CONTROLLER_IP="${CONTROLLER_IP:-10.0.0.11}"
CONTROLLER_NETMASK="${CONTROLLER_NETMASK:-255.255.255.0}"
CONTROLLER_CIDR="${CONTROLLER_CIDR:-${CONTROLLER_IP}/24}"
CONTROLLER_NAMESERVERS="${CONTROLLER_NAMESERVERS:-8.8.8.8}"
CONTROLLER_HOSTNAME="${CONTROLLER_HOSTNAME:-coa-lab}"
PROVIDER_INTERFACE_NAME="${PROVIDER_INTERFACE_NAME:-eth1}"
MANAGEMENT_INTERFACE_NAME="${MANAGEMENT_INTERFACE_NAME:-eth0:1}"
INTERNET_INTERFACE_NAME="${INTERNET_INTERFACE_NAME:-eth0}"
NAT_INTERFACE_NAME="${NAT_INTERFACE_NAME:-eth2}"
OVERLAY_INTERFACE_IP_ADDRESS="${OVERLAY_INTERFACE_IP_ADDRESS:-${CONTROLLER_IP}}"

# OpenStack Network Parameters
PROVIDER_NETWORK_TYPE="${PROVIDER_NETWORK_TYPE:-flat}"
PROVIDER_PHYSICAL_NETWORK="${PROVIDER_PHYSICAL_NETWORK:-provider}"
PROVIDER_SUBNET_RANGE="${PROVIDER_SUBNET_RANGE:-203.0.113.0/24}"
PROVIDER_SUBNET_ALLOCATION_START="${PROVIDER_SUBNET_ALLOCATION_START:-203.0.113.200}"
PROVIDER_SUBNET_ALLOCATION_END="${PROVIDER_SUBNET_ALLOCATION_END:-203.0.113.220}"
PROVIDER_SUBNET_GATEWAY="${PROVIDER_SUBNET_GATEWAY:-203.0.113.1}"
PROVIDER_SUBNET_DNS_SERVER="${PROVIDER_SUBNET_DNS_SERVER:-8.8.8.8}"
PUBLIC_SUBNET_RANGE="${PUBLIC_SUBNET_RANGE:-192.168.99.0/24}"
PUBLIC_SUBNET_ALLOCATION_START="${PUBLIC_SUBNET_ALLOCATION_START:-192.168.99.2}"
PUBLIC_SUBNET_ALLOCATION_END="${PUBLIC_SUBNET_ALLOCATION_END:-192.168.99.254}"
PUBLIC_SUBNET_DNS_SERVER="${PUBLIC_SUBNET_DNS_SERVER:-8.8.8.8}"
PUBLIC_SUBNET_GATEWAY="${PUBLIC_SUBNET_GATEWAY:-192.168.99.1}"
PRIVATE_SUBNET_RANGE="${PRIVATE_SUBNET_RANGE:-192.168.1.0/24}"
PRIVATE_SUBNET_ALLOCATION_START="${PRIVATE_SUBNET_ALLOCATION_START:-192.168.1.2}"
PRIVATE_SUBNET_ALLOCATION_END="${PRIVATE_SUBNET_ALLOCATION_END:-192.168.1.254}"
PRIVATE_SUBNET_GATEWAY="${PRIVATE_SUBNET_GATEWAY:-192.168.1.1}"
PRIVATE_SUBNET_DNS_SERVER="${PRIVATE_SUBNET_DNS_SERVER:-8.8.8.8}"
INCOGNITO_SUBNET_RANGE="${INCOGNITO_SUBNET_RANGE:-192.168.66.0/24}"
INCOGNITO_SUBNET_ALLOCATION_START="${INCOGNITO_SUBNET_ALLOCATION_START:-192.168.66.2}"
INCOGNITO_SUBNET_ALLOCATION_END="${INCOGNITO_SUBNET_ALLOCATION_END:-192.168.66.254}"
INCOGNITO_SUBNET_GATEWAY="${INCOGNITO_SUBNET_GATEWAY:-192.168.66.1}"
INCOGNITO_SUBNET_DNS_SERVER="${INCOGNITO_SUBNET_DNS_SERVER:-8.8.8.8}"

# Passwords
COMMON_PASSWORD="${COMMON_PASSWORD:-openstack}"
RABBIT_PASS="${RABBIT_PASS:-${COMMON_PASSWORD}}"
KEYSTONE_DBPASS="${KEYSTONE_DBPASS:-${COMMON_PASSWORD}}"
GLANCE_DBPASS="${GLANCE_DBPASS:-${COMMON_PASSWORD}}"
GLANCE_PASS="${GLANCE_PASS:-${COMMON_PASSWORD}}"
NOVA_DBPASS="${NOVA_DBPASS:-${COMMON_PASSWORD}}"
NOVA_PASS="${NOVA_PASS:-${COMMON_PASSWORD}}"
PLACEMENT_DBPASS="${PLACEMENT_DBPASS:-${COMMON_PASSWORD}}"
PLACEMENT_PASS="${PLACEMENT_PASS:-${COMMON_PASSWORD}}"
NEUTRON_DBPASS="${NEUTRON_DBPASS:-${COMMON_PASSWORD}}"
NEUTRON_PASS="${NEUTRON_PASS:-${COMMON_PASSWORD}}"
OCTAVIA_DBPASS="${OCTAVIA_DBPASS:-${COMMON_PASSWORD}}"
OCTAVIA_PASS="${OCTAVIA_PASS:-${COMMON_PASSWORD}}"
SWIFT_PASS="${SWIFT_PASS:-${COMMON_PASSWORD}}"
CINDER_DBPASS="${CINDER_DBPASS:-${COMMON_PASSWORD}}"
CINDER_PASS="${CINDER_PASS:-${COMMON_PASSWORD}}"
HEAT_DBPASS="${HEAT_DBPASS:-${COMMON_PASSWORD}}"
HEAT_PASS="${HEAT_PASS:-${COMMON_PASSWORD}}"
BARBICAN_DBPASS="${BARBICAN_DBPASS:-${COMMON_PASSWORD}}"
BARBICAN_PASS="${BARBICAN_PASS:-${COMMON_PASSWORD}}"
METADATA_SECRET="${METADATA_SECRET:-${COMMON_PASSWORD}}"
ADMIN_PASS="${ADMIN_PASS:-${COMMON_PASSWORD}}"
DEMO_PASS="${DEMO_PASS:-${COMMON_PASSWORD}}"
SHERLOCK_PASS="${SHERLOCK_PASS:-${COMMON_PASSWORD}}"

# NOVNC Proxy base URL for VirtualBox with Forwarded Ports 6080->6080
NOVNCPROXY_BASE_URL="${NOVNCPROXY_BASE_URL:-http://${CONTROLLER_IP}:6080/vnc_auto.html}"

OS_DATA_VG="${OS_DATA_VG:-os-data}"

# Swift devices

SWIFT_DEV_1_1="${SWIFT_DEV_1_1:-swift11}"
SWIFT_DEV_1_2="${SWIFT_DEV_1_2:-swift12}"
SWIFT_DEV_2_1="${SWIFT_DEV_2_1:-swift21}"
SWIFT_DEV_2_2="${SWIFT_DEV_2_2:-swift22}"

# Cinder devices

CINDER_VOL1="${CINDER_VOL1:-cinder-vols1}"
CINDER_VOL2="${CINDER_VOL2:-cinder-vols2}"
